### ISSUE TITLE
Questions about the step function

### ISSUE THREAD

**Issue by samreid** [phetsims/inverse-square-law-common#10]
@jessegreenberg said he had questions about the step function.  It looks like there is a numerical solution to adjusting the positions within constraints which was added in this commit:
https://github.com/phetsims/gravity-force-lab/commit/293f8b4f1cdf3edeca96b70e0920d28d47e61937

I suspect there is an analytical solution to this which may be simpler and more direct (and not susceptible to failure in corner cases).

**Comment by mbarlow12** [comment]
Yesterday, @jessegreenberg and I discussed using Property.multilink() to check bounds & overlap on any change to radius or position on either object. We were unsure if there was a particular reason that checking was implemented in step in the first place.

Also, I'm hoping to find a better solution that empirically setting the width of the puller group in the model. Since the puller & rope are purely in the view, perhaps having 2 sets of constraints would be preferable.

**Comment by jessegreenberg** [comment]
Thanks @samreid that was one thought we had.  As @mbarlow12 mentioned, we were also wondering about taking the solution out of step and linking to location and radius Properties.

I found it confusing that object location is corrected in the drag handler (in view coordinates) and in the step function (in model coordinates).  Since there is handling in step, it doesn't seem like the drag handler corrections have any impact.

> perhaps having 2 sets of constraints would be preferable.

I am not too sure what you mean by this, can you please clarify?

**Comment by mbarlow12** [comment]
Sure—my thought was that the model would only restrict the location of the charge/mass object themselves, ignoring the size of the puller. Then either the screenView or object node would offer a separate constraint that would take the puller's width into account.

I'm not sure if this is a good approach, but I think that it keeps the view and model and little more cleanly separated.

**Comment by mbarlow12** [comment]
@jessegreenberg would you check over my update for this? Thanks!

**Comment by jessegreenberg** [comment]
Thanks @mbarlow12 I think this is the right idea.  I am noticing some strange behavior after the update though, could you please take a look?  For instance, it is possible to get the objects to overlap, and the objects are on top of each other after pressing reset all.

**Comment by jessegreenberg** [comment]
It looks like the new solution removed ```PULL_OBJECT_WIDTH``` (an empirically determined constant), but the calculation only considers radius and min separation.  Will it be accurate without considering the width of the puller/pusher?

**Comment by jessegreenberg** [comment]
@mbarlow12 could you add some documentation about how using the new approach with ```currentMidPoint``` is working?

**Comment by jessegreenberg** [comment]
```js
      if ( currentMidpoint < maxLeftMidpoint ) {

        // object1 is at boundary, move object2
        updatedObject2Position = updatedObject1Position + minCenterSeparation;
      } else if ( currentMidpoint > maxRightMidpoint ) {

        // object2 is at boundary, move object1
        updatedObject1Position = updatedObject2Position - minCenterSeparation;
      }
```

If I understand correctly, should these corrections include the object radius?

**Comment by jessegreenberg** [comment]
It looks like we are setting the position of both objects after left and right boundary conditions, I am wondering if this is why the objects are doing some overlapping now?

```js
      if ( Math.abs( updatedObject2Position - updatedObject1Position ) < minCenterSeparation ) {
        updatedObject1Position = currentMidpoint - ( self.minSeparationBetweenObjects + object1Radius );
        updatedObject2Position = currentMidpoint + ( self.minSeparationBetweenObjects + object2Radius );
      }

      if ( updatedObject1Position !== object1Position ) {
        updatedObject1Position = Util.toFixedNumber( updatedObject1Position, DISTANCE_DECIMAL_PRECISION );
        updatedObject1Position = self.snapToGrid( updatedObject1Position );
        self.object1.positionProperty.set( updatedObject1Position );
      }
```

**Comment by samreid** [comment]
@zepumph and I identified a problem with this implementation in #91, @jessegreenberg and @mbarlow12 can you please investigate?

**Comment by mbarlow12** [comment]
@samreid I reimplemented the old step function and commented out my changes, so the fuzz issue is at least patched for now. I'd hoped the recursive strategy might not cause any issues outside of the function itself. We'll find another solution.

@jessegreenberg the midpoint strategy was in an effort to avoid the incremental adjustments to position that were there previously. I'd also thought that it might allow us to make fewer comparisons. I'll be back around lunch today, so we can discuss then about it.

**Comment by jessegreenberg** [comment]
@mbarlow12 and I worked on this today.  We came up with a solution used in step to restrict min and max positions of each object.  It is working nicely, and no longer causes the problem in phetsims/gravity-force-lab#91.

It is working great except that sometimes in coulombs law, I am sometimes able to push one of the charges with another charge.

**Comment by mbarlow12** [comment]
Seems like this is done. Closing.
