### ISSUE TITLE
Fix puller image

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#11]
During status meeting @arouinfar noticed that one of the images arms were too low.  Comparing the checked in images, it looks like pull_figure_24.png is the problem.  @mbarlow12 we might have the wrong image checked in, we compared pull_figure_24.png to the latest images that provided by @arouinfar and the arms look lower in our image.

Would you mind updating the image?

**Comment by mbarlow12** [comment]
Thanks for spotting—I'll update in the next commit.
