### ISSUE TITLE
zero force image pusher visible when force isn't zero

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#14]
This is might be good for coulombs-law (I am not sure), but it is a problem for gravity-force-lab-basics and gravity-force-lab.

I think the main problem is that the zero force image is added to the collection of pull images, which is used by GFL and GFLB.  Moving to the other collection might fix this problem.

But I think PullerPusherNode might be more clear if zeroForceImage wasn't in either collection.  Right now, there is special logic to avoid the zero force image
```js
      if ( force !== 0 && index === this.zeroForceIndex ) {
        index += ( force > 0 ) ? 1 : -1;
      }
```

If it were separate and only displayed when force === 0, the above might not be necessary.

**Comment by jessegreenberg** [comment]
@mbarlow12 do you have any thoughts about this?  Would you be OK separating the zero force image?

**Comment by mbarlow12** [comment]
I think the difficulty is that we're iterating over the array of images and setting the visibility. If we keep it separate, then we need to first find the currently visible image, hide it, and display the zero image.

The other solution is to only include the zeroForceImage in the collection when attractNegative is true instead of including it in pullImages at the outset.

**Comment by jessegreenberg** [comment]
@mbarlow12 do you have a preference? I prefer the first solution.

> If we keep it separate, then we need to first find the currently visible image, hide it, and display the zero image.

This doesn't seem like too much of an issue to me.  I find it more confusing that zeroForceImage is in either group since it is neither a puller nor a pusher.

**Comment by mbarlow12** [comment]
@jessegreenberg The zeroForceImage is now separate, and if attractNegative is true, our array construction is:

`this.pullerPusherImages = pushImages.concat( zeroForceImage ).concat( pullImages );`

Does that work for you?

**Comment by jessegreenberg** [comment]
I think that should work @mbarlow12, thanks!

Did you mean to commit the change to the step function?  I am seeing some strange behavior now.

**Comment by jessegreenberg** [comment]
But I verified that the images look good in gravity-force-lab-basics. Closing.
