### ISSUE TITLE
Sim size

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#22]
When we add the "atomic" pushers, sims that use this repo will have a lot of images.

32 pull images * 32 push images * 2 (one set for atomic, one set for macro) = 128 images.

Each image is 20-30KB, so that will total to ~3.84 MB in images alone. So the sim will likely total around 4.5 MB which is much larger than most sims right now.

@ariel-phet thoughts on whether or not this is OK? In the meantime @arouinfar is going to try to reduce the size of images to bring that number down.

**Comment by ariel-phet** [comment]
@jessegreenberg I thought FAMB uses a similar strategy (lots of images). How much total image space is being used in FAMB?

**Comment by ariel-phet** [comment]
Looks to me like each of the pusher pictures is around 5-6 KB

**Comment by jessegreenberg** [comment]
Excellent, @arouinfar verified that the images can be exported at about 8 KB, which should keep the sim <2.5 MB.

**Comment by jessegreenberg** [comment]
New images will be exported and added as part of #23, so closing this issue.
