### ISSUE TITLE
Add atomic pushers

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#23]
coulombs-law needs new images for the pushers used in the atomic screen.

@arouinfar will send assets to @mbarlow12 to add.

We also need to decide how they should be added and I see a few options since they will add ~.5MB to the sim.

- Add images to ISLCPullerNode, enabling them optionally. This will add 0.5MB to GFL and GFL:B, even though those sims do not use these images. But the code will be cleaner (probably).
- Add the images somewhere in CL, passing an array of images to ISLCPullerNode. Will keep GFL and GFL:B smaller, but I am not crazy about this solution.

**Comment by jessegreenberg** [comment]
@mbarlow12 what do you think?

**Comment by arouinfar** [comment]
Assets have been emailed to @mbarlow12 and @jessegreenberg.

**Comment by mbarlow12** [comment]
New images for atomic pullers/pushers have been uploaded; however, with the updates from https://github.com/phetsims/inverse-square-law-common/issues/21, the respective movement/change in the pullers and the arrows.

This can be alleviated by passing in a narrower force range to the pullers. In this case, we lose articulation at large force values where the pullers are maxed but see some movement at smaller values that syncs better with the arrow scaling.

**Comment by mbarlow12** [comment]
Above changes were made in https://github.com/phetsims/coulombs-law/commit/9e47dd3ebb27e5062b7aa091c50b39a2852f0e22.

**Comment by jessegreenberg** [comment]
@mbarlow12 nice work, the new images look great in the sim! In https://github.com/phetsims/coulombs-law/commit/9e47dd3ebb27e5062b7aa091c50b39a2852f0e22 the arrow scale constant was reduced from 50000 to 500. Was that intentional?

**Comment by jessegreenberg** [comment]
@mbarlow12 is there anything else to do for this issue?
