### ISSUE TITLE
branch: augmented-arrows

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#24]
Branch is a snapshot of sim behavior as of 12/18/17, to save progress as we explore #21. Arrows have some "augmented" min width so that they are always visible. In #21, we are going to try removing this.

**Comment by jessegreenberg** [comment]
This branch should be pruned before the sim is deployed.

**Comment by jessegreenberg** [comment]
Actually, we are happy with the behavior in this branch and that behavior is already in master so this branch can be pruned now.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
