### ISSUE TITLE
Document ISLCObjectNode's enabledProperty var

### ISSUE THREAD

**Issue by samreid** [phetsims/inverse-square-law-common#25]
This code is in ISLCObjectNode.js

```js
    // TODO: please document this -- it is unclear what it is for or if it is necessary
    var enabledProperty = new BooleanProperty( true, {
      tandem: tandem.createTandem( 'enabledProperty' )
    } );
```

@jessegreenberg can you please document what the enabled property is for, so that I can understand how it should appear in the PhET-iO instrumentation?

Should be done before https://github.com/phetsims/gravity-force-lab-basics/issues/22 so I'll mark it with the same priority.

**Comment by jessegreenberg** [comment]
It is just a Property that  is required for the Node to behave like an AccessibleSlider. ISLCObjects are always enabled, but it is passed to AccessibleSlider.initializeAccessibleSlider. I added documentation for this. Assigning to @samreid in case further discussion is necessary.

**Comment by samreid** [comment]
Thanks for explaining this, I tried inlining it to make it more clear that it is a temporary variable just for the accessible slider, and not something stateful and persistent for the ISLCObjectNode, can you please review?  Close if it seems OK to you.

**Comment by jessegreenberg** [comment]
Thanks @samreid that looks good to me, closing.
