### ISSUE TITLE
ISLCCheckboxPanel TODO clarification

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/inverse-square-law-common#27]
@samreid We noticed some TODOs you added in a few places and were hoping to get some clarification. For the comment referenced below, we'd hoped to avoid repeating a lot of Text and tandem creations in the various screens that use this type.

https://github.com/phetsims/inverse-square-law-common/blob/7ed73fdef0d6bf22b9a59d4b96225f5fc1c88600/js/view/ISLCCheckboxPanel.js#L47-L65

Let me know if this is considered bad practice. Thanks!

**Comment by samreid** [comment]
In the preceding commits, I factored out ISLCCheckboxItem as a way to share code for the text and tandem creations. `ISLCCheckboxPanel.js` is correspondingly simpler.

@jessegreenberg I had to manually merge our commits on GravityForceLabBasicsScreenView.js, can you make sure I did it correctly?

@mbarlow12 and/or @jessegreenberg can you please review the changes?  Also, I'm not too familiar with Gravity Force Lab: Basics, Gravity Force Lab or Coulomb's Law, so can you please carefully check if they still work properly?

**Comment by samreid** [comment]
Oops, the preceding commit belongs in https://github.com/phetsims/capacitor-lab-basics/issues/218, sorry.

**Comment by mbarlow12** [comment]
I had some pull issues and didn't see the most recent CL changes. The above commits are redundant and don't really change anything. @samreid all the changes look ok to me. Thanks for the refactor.

**Comment by jessegreenberg** [comment]
I am also having a hard time pulling these changes. @mbarlow12 were you ever able to pull?

**Comment by mbarlow12** [comment]
Yes—I wasn't sure if it was a strange error with my text editor, but I pulled and rebased.  Since the sim was working and grunt was clean, I pushed my commits as well.

**Comment by jessegreenberg** [comment]
Hmm, looks like I do have everything. New type ISLCCheckBoxItem wasn't appearing in my local copy but it is there now.

**Comment by mbarlow12** [comment]
@jessegreenberg any reason I shouldn't close this?
