### ISSUE TITLE
Rename Mass.js to ISLCMass.js

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#31]
Considering the naming of types in this repo and the fact that there are other "Mass" types for other sims in the project, I might recommend renaming Mass to  ISLCMass. Thoughts @mbarlow12?

**Comment by jessegreenberg** [comment]
For #30

**Comment by mbarlow12** [comment]
I don't think I agree, and I'm not sure that it belongs in the common repo. I'd vote to either 1) move it to both GFL & GFLB or 2) move it to GFL and inherit it in GFLB. They both have some trade offs, but I think it's a cleaner code organization/hierarchy.

**Comment by jessegreenberg** [comment]
> They both have some trade offs, but I think it's a cleaner code organization/hierarchy.

Can you elaborate? What is the benefit of having GFLB dependent on GFL? At the moment all three sims are only dependent on inverse-square-law-common.

**Comment by jessegreenberg** [comment]
Ah, maybe you were thinking types in ISLC should be agnostic of mass or charge?

**Comment by jessegreenberg** [comment]
If that is the case I do prefer option 2 of https://github.com/phetsims/inverse-square-law-common/issues/31#issuecomment-369418936 to avoid duplicated code. @mbarlow12 would you mind working on this transition if you think it is best? gravity-force-lab will need to be added as a dependency to gravity-force-lab-basics in package.json.

**Comment by mbarlow12** [comment]
@jessegreenberg sure thing.
