### ISSUE TITLE
Move ISLCObjectNode arrowOptionKeys to constants?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#34]
I believe the options defined in arrowOptionKeys are not instance specific and it might be more conventional to have these documented as a constant above the constructor. @mbarlow12 thoughts?

for #30

**Comment by jessegreenberg** [comment]
Ditto for pullerOptionKeys?

**Comment by mbarlow12** [comment]
@jessegreenberg I'm a little confused on the question. Almost all those options have different values depending on which object and/or sim is creating the instance. I suppose we could create some kind of enum type and simply pass a 'left' or 'right' option at instantiation that would handle the rest of them. Is that the idea?

**Comment by jessegreenberg** [comment]
My thought was that the actual array arrowOptionKeys does not change for each instance, those strings are just iterated with _.pick. It also might be easier to find the arrow specific options if they are  closer to the top of the file.

ALIGNMENT_CONTAINER_OPTION_KEYS in AlignBox is kind of what I was thinking.

**Comment by mbarlow12** [comment]
Ah, yes. Sure thing!
