### ISSUE TITLE
Sim needs an assets directory

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#39]
This repo does not have an assets directory to hold the original assets from .aigggggggggg.

@mbarlow12 can you coordinate with @arouinfar to get the original files and place them in a directory called "assets" under inverse-square-law-common?

For #30.

**Comment by arouinfar** [comment]
@jessegreenberg I believe I included the source .ai file with the .png assets, but I know we went through a few iterations on the assets, so they may be hard to track down.

I've emailed the final .ai assets to @mbarlow12. Please let me know if there's anything else you need.
