### ISSUE TITLE
Type names should be consistent

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#4]
Right now, types use a mix of naming strategies like

```ISLCheckboxPanel``` ```InverseSquareLawCommonConstants``` and ```InverseSquareLawModel```.

Personally I like the pattern```ISLType```, but the naming should be consistent.

**Comment by jessegreenberg** [comment]
@mbarlow12 Ill assign this to both of us for whoever gets to it first.

**Comment by jessegreenberg** [comment]
Regarding the comment in https://github.com/phetsims/inverse-square-law-common/issues/4#issue-224595995, after sitting for a while, I think the best names for types in this repo are ```ISLCType```, since it follows naming conventions for other sims which build an acronym based on the repo name.

**Comment by jessegreenberg** [comment]
So ```ISLCQueryParameters```, ```ISLCObjectNode```, ```ISLCModel```, and so on.

**Comment by mbarlow12** [comment]
InverseSquareLawCommonConstants --> ISLCConstants

**Comment by mbarlow12** [comment]
InverseSquareLawObject -> ISLCObject

**Comment by mbarlow12** [comment]
ObjectNode -> ISLCObjectNode

**Comment by mbarlow12** [comment]
Remaining types:

- [ ] InverseSquareLawGridNode
- [ ] ObjectControl
- [ ] PullerPusherNode

**Comment by mbarlow12** [comment]
Completed—closing.
