### ISSUE TITLE
Change string keys

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#43]
For #30 and dependent on #26.  I would recommend making these keys a little more friendly for translators.
```json
  "force-description-pattern-target_source": {
    "value": "Force on {0} by {1}"
  },
  "force-description-pattern-target_source_value": {
    "value": "Force on {0} by {1} = {2} N"
  },
```
`source` and `source-value` don't really signify the purpose to me. @mbarlow12 what do  you think about 
`forceOnObjectByObjectPatternString` and
`forceOnObjectByObjectWithUnitsPatternString`

Do you know if these keys were copied from gravity-force-lab strings or did we come up with them as we made ISLC?

**Comment by mbarlow12** [comment]
Works for me.

**Comment by mbarlow12** [comment]
Completed, but I suppose we can wait to tackle https://github.com/phetsims/inverse-square-law-common/issues/26 until we're closer to releasing the sim. I'll keep my assignment.
