### ISSUE TITLE
[GFL] Slider colors have lost their saturation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/inverse-square-law-common#48]
@arouinfar can we do something about the slider colors? Here is how they look:

<img width="1187" alt="screen shot 2018-05-21 at 11 17 10 am" src="https://user-images.githubusercontent.com/5863899/40320693-c05f8f8e-5ce9-11e8-81f3-b02831fab859.png">

I don't like the washed out look of the sliders, which I believe is a consequence of the commits in #47. I believe the code chooses the slider color based on some initial values of the mass color, the mass' `baseColorProperty`, so this was maybe an unintentional change.

My biggest reason for disdain is that these colors are dangerously close to the "highlight/interaction" colors. Essentially, it looks like I am interacting with the sliders in the above screenshot (I'm not), and when you hover your mouse over them the change is hardly discernible. There are probably bigger reasons this change is harmful that I just can't think of 😄. I suppose they also just don't stand out as much anymore?

So can we do one or more of these to fix the slider colors?

1. Revert the slider colors back to their full saturation while keeping the changes with #47. I believe this would require some work to remove the slider-mass color dependency.

2. Have the sliders change saturation dynamically to match the mass color as it changes. This would still have the sliders look washed out, and even completely white, at some mass values...but could be cool! This is probably a bad idea....

@arouinfar you don't have to do either of the things above. Just thought I would write my thoughts. This is only affecting GFL, not any of the other ISL sims.

**Comment by arouinfar** [comment]
Good catch @phet-steele. This is an unintended consequence of #47. We could probably change the hover color so the thumb looks more interactive, but I think the bigger problem is the general lack of thumb brightness and the poor contrast with the panels. I'd be in favor of option (1), which also works well for the `numberPicker`s in GFLB.
![image](https://user-images.githubusercontent.com/8419308/40329783-ee007e26-5d07-11e8-96ce-8ddbf8650336.png)

@mbarlow12 can you please update the slider thumbs to fully saturated blue/red?

**Comment by mbarlow12** [comment]
Ah, yes— @phet-steele  is correct, the thumbs are looking at the initial color of the mass objects. I've made the updates to set the thumb color separately.

**Comment by arouinfar** [comment]
Master looks good @mbarlow12. If there isn't any outstanding work, please close.

**Comment by mbarlow12** [comment]
Thanks @arouinfar. Closing.
