### ISSUE TITLE
Disable Scientific Notation when Force Values off

### ISSUE THREAD

**Issue by arouinfar** [phetsims/inverse-square-law-common#51]
In https://github.com/phetsims/coulombs-law/issues/47 we considered indenting the Scientific Notation checkbox since it has child/parent relationship with Force Values, but [ultimately decided against it](https://github.com/phetsims/coulombs-law/issues/47#issuecomment-364229995).

However, we did not consider the case of simply disabling/graying out the Scientific Notation checkbox when Force Values is off. This was something that came up in yesterday's meeting to discuss the static descriptions for Coulomb's Law, and again this morning when meeting with @terracoda. 

The static descriptions would be a bit clearer, because the screen reader would indicate that the checkbox is disabled. I think this is also better UX for all users.

![image](https://user-images.githubusercontent.com/8419308/40853286-c4fca834-658a-11e8-880f-a1b3c1afef05.png)

What do you think @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar that change works for me

**Comment by arouinfar** [comment]
Thanks @ariel-phet!

@mbarlow12 can you please make this change?

**Comment by mbarlow12** [comment]
Will do! @arouinfar will this apply to GFL as well?

**Comment by arouinfar** [comment]
Great question @mbarlow12! Yes, this change would apply to GFL, as well.

**Comment by mbarlow12** [comment]
New dev depolyment:

https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.17/phet/coulombs-law_en_phet.html

**Comment by arouinfar** [comment]
Thanks @mbarlow12. CL and GFL are looking good!
