### ISSUE TITLE
Options in ISLCObjectControlPanel

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#52]
It seems like some of the options here are not used. For instance, I can't find where all of the options prefixed by `value` are used, are they passed directly to anything? I don't think so because options are generally filtered before being passed to things, and Panel doesn't use them. I also recommend changing these options to the "nested options" style that was agreed on, instead of using `_.pick` and _.omit could we use 
```js
options = _.extend( {
  //...
  numberControlOptions: {},
  panelOptions: {},
  //...
} );

options.panelOptions = _.extend( {...}, options.panelOptions );
options.numberControlOptions = _.extend( {...}, options.numberControlOptions );
```

Maybe if options are reused in a few places this wouldn't work but that also seems like an issue.

**Comment by jessegreenberg** [comment]
Found while looking into https://github.com/phetsims/gravity-force-lab/issues/105.

**Comment by jessegreenberg** [comment]
Ill do the same for tickLabelOptions.

**Comment by jessegreenberg** [comment]
I went ahead with this and updated usages in CL and GFL. @mbarlow12 can you please review?

**Comment by mbarlow12** [comment]
@jessegreenberg looks good to me. Thanks for handling while I was away. Feel free to close.
