### ISSUE TITLE
visibility of line in ISLCLegendNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#55]
I noticed on CT that CL was using a reference to the legendArrowLine in ISLCLegendNode, and it looks like that was removed. I made the legendArrowLine `@public (read-only)` for this. Commit following, does this look right @mbarlow12?

I was watching this because I thought this might have an impact on the release of coulombs-law, but it looks like this change was well after 1.0 shas were taken and was only in master.

**Comment by mbarlow12** [comment]
Thanks @jessegreenberg. It looks like I accidentally made the changes in `coulombs-law-1.0` and didn't pull them into master. Too much branch switching & picking today :/
