### ISSUE TITLE
Add semi-transparent background behind Force string/value

### ISSUE THREAD

**Issue by arouinfar** [phetsims/inverse-square-law-common#56]
Suggested by @kathy-phet in https://github.com/phetsims/coulombs-law/issues/103:

> It seems like the white text of the force readout on the left hand ball could benefit from having a semi-transparent black background box so when it overlaps the line dropping down to the ball on the right it is a bit more readable with less interference from the line.
>
>This is minor and can be considered when outfitted with dynamic description.

I like this suggestion, but I think we could add a semi-transparent rectangle that matches the background color behind the entire force string (not just the value). 
![image](https://user-images.githubusercontent.com/8419308/50379483-f6671800-0607-11e9-9759-fe9d71c888ad.png)

I think this is a change we should make across all ISLC sims, so opening an issue in the common repo.

Assigning to @mbarlow12. This is a change that should be made before GFLB is released (or GFL is redeployed with descriptions -- not sure which will happen first).

**Comment by zepumph** [comment]
Just seeing this now. I will get to this before GFLB is published

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/60467199-6a5f2a00-9c02-11e9-9ddb-637a40e84e67.png)

![image](https://user-images.githubusercontent.com/6856943/60467204-734ffb80-9c02-11e9-8aed-2187bbd8a629.png)


@arouinfar could I get a bit more direction on this. Here is one potential solution with a black background, with opacity at 40%.

I was thinking a few potential changes:
* Maybe make the color the same as the background color (so dependent on the sim)
* Maybe dilate the background a bit around the text, for some padding


What do you think?


I won't commit anything yet. Here is the patch I worked on for this.

<details>

```
Index: js/view/ISLCForceArrowNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/view/ISLCForceArrowNode.js	(revision 0bfd0a4f333b8be05588d3c890423ba9257aef92)
+++ js/view/ISLCForceArrowNode.js	(date 1562015936683)
@@ -10,6 +10,7 @@
   'use strict';
 
   // modules
+  const Rectangle = require( 'SCENERY/nodes/Rectangle' );
   var ArrowNode = require( 'SCENERY_PHET/ArrowNode' );
   var inherit = require( 'PHET_CORE/inherit' );
   var inverseSquareLawCommon = require( 'INVERSE_SQUARE_LAW_COMMON/inverseSquareLawCommon' );
@@ -98,6 +99,11 @@
     this.arrow = new ArrowNode( 0, -options.forceArrowHeight, 200, -options.forceArrowHeight, arrowOptions );
 
     Node.call( this, {} );
+
+    // @private
+    this.arrowTextBackground = new Rectangle( 0, 0, 1000, 1000, { fill: 'black', opacity: .3 } );
+    this.addChild( this.arrowTextBackground );
+
     this.addChild( this.arrowText );
     this.addChild( this.arrow );
 
@@ -154,6 +160,12 @@
       else {
         this.arrowText.center = arrowTextCenter;
       }
+
+      // set the background layout too
+      this.arrowTextBackground.rectWidth = this.arrowText.width;
+      this.arrowTextBackground.rectHeight = this.arrowText.height;
+      this.arrowTextBackground.center = this.arrowText.center;
+
     },
 
     /**
@@ -192,14 +204,21 @@
             }
           }
 
-          this.arrowText.text = StringUtils.fillIn( forceOnObjectByOtherObjectWithUnitsPatternString, { thisObject: this.label, otherObject: this.otherObjectLabel, value: formattedString } );
+          this.arrowText.text = StringUtils.fillIn( forceOnObjectByOtherObjectWithUnitsPatternString, {
+            thisObject: this.label,
+            otherObject: this.otherObjectLabel,
+            value: formattedString
+          } );
         }
         else {
           throw new Error( 'ISLCForceArrowNode.updateLabel() requires a decimal value' );
         }
       }
       else {
-        this.arrowText.text = StringUtils.fillIn( forceOnObjectByOtherObjectPatternString, { thisObject: this.label, otherObject: this.otherObjectLabel } );
+        this.arrowText.text = StringUtils.fillIn( forceOnObjectByOtherObjectPatternString, {
+          thisObject: this.label,
+          otherObject: this.otherObjectLabel
+        } );
       }
     }
   } );

```

</details>

**Comment by arouinfar** [comment]
> @arouinfar could I get a bit more direction on this. Here is one potential solution with a black background, with opacity at 40%.

Sure thing @zepumph! The screenshot of Coulomb's Law in https://github.com/phetsims/inverse-square-law-common/issues/56#issuecomment-507429873 looks pretty readable to me, so opacity of 40% sounds good.

> Maybe make the color the same as the background color (so dependent on the sim)

Agreed, the color should match the sim background, so it would be different across all three ISLC sims. The idea is to wash out the dashed line so the string becomes more readable, but we don't actually want the box around the text to be visible otherwise.

>Maybe dilate the background a bit around the text, for some padding

This could make the text near the dashed line ever-so-slightly more readable, so let's go for it. I don't think it needs much dilation, maybe just 1 or 2 px of extra padding.

**Comment by zepumph** [comment]
That sounds excellent. I accidentally committed the patch, but I will sort things out now, after I deal with https://github.com/phetsims/inverse-square-law-common/issues/73

**Comment by zepumph** [comment]
Sorry I misspoke earlier, the opacity that you see is 30%. In the above commits I made the color dependent on the background color. @arouinfar what do you think?

**Comment by arouinfar** [comment]
>  the opacity that you see is 30%

👍 

>  @arouinfar what do you think?

The ISLC sims all look great in master, thanks @zepumph!

**Comment by zepumph** [comment]
Good deal! I'm not planning on maintenance releasing this. Let me know if you feel differently. So things will be picked up next publication. Closing
