### ISSUE TITLE
Defaults provide room for sneaky errors

### ISSUE THREAD

**Issue by zepumph** [phetsims/inverse-square-law-common#58]
There are multiple places in this suite where label/string default options are expected to be overwritten, but the default is just a string, like "generic label" or something. 

Another similar pattern is that abstract methods in base classes through throw errors when called, but sometimes it is easier to comment that out since coulombs-law isn't being worked on in parallel. 

I talked to @mbarlow12 about one case before (I couldn't find the issue), about `ForceDescriber.getForceVectorIndex`. It makes sense for that to be commented out, but I think we need a central issue to point all the TODOs to so that it doesn't become unweildy.

Again this issue isn't saying that anything is wrong necessarily, but instead just saying that documentation is warranted so  that once everything is implemented, we can change things to hard failures when inappropriate options/methods are not properly provided.

**Comment by mbarlow12** [comment]
@zepumph at least regarding the default label options, my thought was to have it be very obvious when something might not be working properly. So if you ever see something like `object 1 label` or `default label` you'd know where to start tracing the bug.

As to the loud failures for abstract methods & classes, one quick solution would be to construct the minimal classes in Coulomb's Law to satisfy implementation but don't work.

**Comment by zepumph** [comment]
> So if you ever see something like object 1 label or default label you'd know where to start tracing the bug.

It is very cool that you have enough attention to detail that this is a loud error for you! Unfortunately I do not. It would be easy for me to gloss over something like this. I also worry if something changes in a few years, when someone isn't working as actively in the repo. I think assertions will be an improvement here, though I understand and agree that they may not have been the best choice while developing to this point. Especially since the ISLC hierarchy can cause headaches when you may have to implement 3 usages of something in the same commit if you want to fail when it isn't provided.

>As to the loud failures for abstract methods & classes, one quick solution would be to construct the minimal classes in Coulomb's Law to satisfy implementation but don't work.

That sounds very nice! I'll look into that.

**Comment by zepumph** [comment]
With the above commit, there are no longer any options with default strings.
