### ISSUE TITLE
no need to replace {{value}} with {0}

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/inverse-square-law-common#59]
See https://github.com/phetsims/scenery-phet/issues/446#issuecomment-460726349

NumberControl and NumberDisplay now support both '{{value}}' and '{0}'.  So...

In ISLCObjectControlPanel.js, this:

`90 valuePattern: StringUtils.fillIn( pattern0Value1UnitsString, { value: '{0}', units: unitString } ),`

can be changed to this:

`90 valuePattern: StringUtils.fillIn( pattern0Value1UnitsString, { units: unitString } ),`

**Comment by jessegreenberg** [comment]
Thanks, done above.
