### ISSUE TITLE
Use VerticalCheckboxGroup instead of custom ISLCCheckboxItem

### ISSUE THREAD

**Issue by zepumph** [phetsims/inverse-square-law-common#66]
I'm unsure why there is a custom is solution here, even after looking at https://github.com/phetsims/inverse-square-law-common/issues/51.

It seems like we should be using VerticalCheckboxGroup, I'll take a look further. From https://github.com/phetsims/gravity-force-lab-basics/issues/134

**Comment by jessegreenberg** [comment]
I think the motivation for removing VerticalCheckboxGroup in #51 was because VerticalCheckboxGroup does not currently support disabling a single checkbox in the group.

**Comment by zepumph** [comment]
@jessegreenberg in the above commits I added support to VerticalCheckboxGroup to support individual options passed to a single checkbox. From that it was easy enough to pass a custom enabledProperty to the scientific notation checkbox. Please review. Note that this changed the layout of the checkbox panel by a few pixels (not greatly). What do you think about this change?

**Comment by jessegreenberg** [comment]
Awesome, thank you! What do you think about changing the order of options for the extend call to
```js
_.extend( {}, options.checkboxOptions, item.options, {
```

so that the group options can be overridden by individual options?

**Comment by zepumph** [comment]
Great idea! I also needed to do some cleanup in terms of how we were passing enabledProperty through (mainly for phet-io related problems). @chrisklus was a great help in simplifying. His idea was to just use the `showForceValuesProperty` as the enabledProperty, so there was no proxy/intermediary needed. @jessegreenberg anything else for this issue?

**Comment by terracoda** [comment]
@zepumph and @jessegreenberg, the disabling option has been working visually, but I don't think it has ever worked in the PDOM. In the screenshot you can see that the disabled check box is focusable and checked.
<img width="696" alt="Screen Shot 2019-07-08 at 5 24 14 PM" src="https://user-images.githubusercontent.com/1902116/60822441-c0edda80-a1a5-11e9-9095-3707bc410e81.png">

This checkbox issue is being tracked in #110.

**Comment by zepumph** [comment]
Sounds good. @terracoda see https://github.com/phetsims/sun/issues/517 for the general solution. Anything else for this issue?

**Comment by jessegreenberg** [comment]
Changes look great, and since the issue @terracoda mentioned is going to be tracked elsewhere I think this can be closed.
