### ISSUE TITLE
Rename convertDistanceMetric?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#72]
It looks like this is a function that formats the value for the descrption, could this be renamed to formatValue or convertPosition? The name made me thing this was possibly responsible for more (and maybe it is!). ForceDescriber has an optional function convertForce so convertPosition felt like a fitting name.

**Comment by jessegreenberg** [comment]
For https://github.com/phetsims/gravity-force-lab-basics/issues/156

**Comment by zepumph** [comment]
I went with `formatDisplayDistance`. What do you think?

**Comment by jessegreenberg** [comment]
Thanks, I like it!
