### ISSUE TITLE
ISLCObjectNode should use nested options

### ISSUE THREAD

**Issue by zepumph** [phetsims/inverse-square-law-common#73]
There is an old pattern used here intead of nested options, which picks out `ARROW_OPTION_KEYS` and `PULLER_OPTION_KEYS` from options passed to `ISLCObjectNode`. This involves duplication, and could be improved.

**Comment by zepumph** [comment]
This was a bit of refactoring, but I like the change. Through it I also removed a lot of unused options, and converted a few to required params where it made sense. @jessegreenberg would you mind reviewing this since it was a fair bit of work. Thanks!

**Comment by jessegreenberg** [comment]
Changes look really good overall and I like how merge is looking. The only thing I noticed is that the pusher images look like they are pushing harder for a given force than they are in the published version.

**Comment by jessegreenberg** [comment]
Scanning through commits, it looks like `pullRangeMultiplier` option was removed from ChargeNode and CoulombsLawAtomicView, that may be the cause.

**Comment by jessegreenberg** [comment]
I think I tracked it down to a different issue, 35ad0608840ab146746cb8a67b69bc32a7163d8f in https://github.com/phetsims/gravity-force-lab-basics/issues/120.

Otherwise things look really good here and I am excited to use merge more.

**Comment by zepumph** [comment]
>Otherwise things look really good here and I am excited to use merge more.

Yes indeed! I have been taking it for a test drive in part for the review in https://github.com/phetsims/phet-info/issues/91. Hopefully we can consider it production ready before too long since wave interference in ISLC sims are about to be published. See that issue before committing fully to that pattern.
