### ISSUE TITLE
Alerting, non-node types should use AlertManager.js

### ISSUE THREAD

**Issue by zepumph** [phetsims/inverse-square-law-common#85]
From https://github.com/phetsims/utterance-queue/issues/13, the new pattern for alerting to descriptionUtteranceQueue is to go through a Node, thus we need non-node types to extend `AlertManager.js` to access said Node.

UPDATE: the common code type is now called `Alerter.js`

**Comment by zepumph** [comment]
Also similar to https://github.com/phetsims/greenhouse-effect/issues/70, in https://github.com/phetsims/utterance-queue/issues/13, @jessegreenberg volunteered to take this on, but I think to begin with I would like to do a first pass. It will be a fair bit of work and I would like to see it done sooner rather than later.

**Comment by zepumph** [comment]
Oh, oops, I see more in the ruler describer, one commit coming in hot!

**Comment by zepumph** [comment]
Ok. Now I think we are ready for a review. In general I just tried to make things as simple as possible. I know we will have work to do if/when we make coulombs law support description.

**Comment by jessegreenberg** [comment]
I reviewed the commits, they look good and maintainable and are good usages of Alerter. I did not verify behavior for ISLC sims after the change. Closing.
