### ISSUE TITLE
Layering issues with mass/charge nodes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#9]
From https://github.com/phetsims/gravity-force-lab-basics/issues/14.  The object nodes are self contained, but this creates layering problems because the arrows and labels of one object will be layered under the dashed line of another object.

![](https://user-images.githubusercontent.com/4051174/27750998-87d222fa-5d97-11e7-9d08-0316cebf0ba6.PNG)

They need to be structured differently, or there needs to be an API that lets the client layer components of the objects.

**Comment by jessegreenberg** [comment]
Or the arrows and labels need to be removed completely from ObjectNode, so client can add them direclty to a ScreenView.  I like this option best.

**Comment by jessegreenberg** [comment]
That option seems best, and makes it impossible to "forget" to add arrows and labels. ObjectNode constructor is pretty large, so this will also make ObjectNode easier to read.

**Comment by jessegreenberg** [comment]
Actually I think in the initial work to generalize inverse-square-law-common we did some refactoring to make all ObjectNode components self contained in the one file.  Unfortunately, with the layering problems, I think we are going to have to proceed with https://github.com/phetsims/inverse-square-law-common/issues/9#issuecomment-316230933

**Comment by jessegreenberg** [comment]
I took a stab at moving the arrow out of ObjectNode.  But there are a few things that are problematic to me.

1) Every ScreenView from an inverse-square-law-common sim will need to register listeners to force to update the arrow node.
2) Every ScreenView will need to handle positioning of the arrow nodes.

This will result in a lot of similar but unique code for each flavor of inverse-square-law-common.

@mbarlow12 recommended another pattern where we layer the arrows in the screen view.  I will look into getting ObjectNode to support this.

**Comment by jessegreenberg** [comment]
@mbarlow12 I took a stab at this and tested it out in coulombs-law.  Would you mind reviewing?

**Comment by mbarlow12** [comment]
Looks good to me. We may just want to consider using a different emitter. It's now the only part of the step function. Thoughts @jessegreenberg ?

**Comment by jessegreenberg** [comment]
@mbarlow12 and I talked about this today.  Since the step function has been added back in #10, it seems fine to keep this emitter for now.  Closing.
